#Travis CI configuration (https://travis-ci.org/)
language: php
sudo: required
dist: trusty
group: stable
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.12
  - hhvm-3.13
  - hhvm-3.14
  - hhvm-3.15
  - nightly
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-3.12
        - php: hhvm-3.13
        - php: hhvm-3.14
        - php: hhvm-3.15
        - php: hhvm-nightly
        - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - composer test-with-coverage
    - composer benchmark

after_success:
  - travis_retry vendor/bin/coveralls -v
