#Travis CI configuration (https://travis-ci.org/)
language: php
sudo: required
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  include:
    - php: hhvm
      env: FORCE_XDEBUG_ENABLE=true
    - php: hhvm-nightly
      env: FORCE_XDEBUG_ENABLE=true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
    # https://github.com/travis-ci/travis-ci/issues/2980
    - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm && $FORCE_XDEBUG_ENABLE == true ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - composer test-with-coverage
    - composer benchmark

after_success:
  - travis_retry vendor/bin/coveralls -v
