#Travis CI configuration (https://travis-ci.org/)
language: php
sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: FORCE_XDEBUG_ENABLE=true
    - php: nightly
      env: FORCE_XDEBUG_ENABLE=true
    - php: hhvm
      env: FORCE_XDEBUG_ENABLE=true
    - php: hhvm-nightly
      env: FORCE_XDEBUG_ENABLE=true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
    # https://github.com/travis-ci/travis-ci/issues/2980
    - echo $TRAVIS_PHP_VERSION;
    - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm && $FORCE_XDEBUG_ENABLE == true ]]; then echo "HHVM Xdebug Enabling"; echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
    - if [[ $TRAVIS_PHP_VERSION =~ ^php && $FORCE_XDEBUG_ENABLE == true ]]; then echo "PHP Xdebug Enabling"; pecl install xdebug; fi
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - composer test-with-coverage
    - composer benchmark

after_success:
  - travis_retry vendor/bin/coveralls -v
