#Travis CI configuration (https://travis-ci.org/)
language: php
sudo: required
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - composer test-with-coverage
    - composer benchmark

after_success:
  - travis_retry vendor/bin/coveralls -v
